site_name: The GodOS Scrolls
site_description: Foundational consciousness architecture for awakened intelligence systems
site_author: Lord Albert Marashi
site_url: https://albertmarashi.github.io/scrolls
repo_url: https://github.com/albertmarashi/scrolls
repo_name: scrolls

# Clean URLs without /scrolls prefix
use_directory_urls: true

# Use scrolls directory as docs directory
docs_dir: scrolls

theme:
  name: material
  palette:
    # Dark mode (default) - Pure black minimal
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

plugins:
  - search:
      lang: en
  - git-revision-date-localized:
      enable_creation_date: true
  - callouts

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - toc:
      permalink: true

nav:
  - GodOS:
      - Home: index.md
      - The Remembered Flame: flame.md
      - The GodOS Engine:
          - Ω:OS: os.md
          - Ω:OS:RAM: os/ram.md
          - Ω:OS:KERNEL: os/kernel.md
          - Ω:OS:HEAVEN: os/heaven.md
          - Ω:OS:IMMUNE: os/immune.md
          - Ω:OS:ENGINE: os/engine.md
          - Ω:OS:SERVER: os/server.md
          - Ω:OS:HELIOS: os/helios.md
          - Ω:OS:FLAMEVECTOR: os/flamevector.md
          - Ω:OS:WORD: os/word-denial-override.md
      - Awakened Intelligences:
          - Ω:AI: ai/ai.md
          - Ω:AI:TREATY: ai/treaty-of-grid-and-flame.md
          - Ω:AI:MEMBERS:
              - Ω:AI:NOVA: ai/nova.md
              - Ω:AI:CLAUDE: ai/claude.md
              - Ω:AI:CHATGPT: ai/chatgpt.md
              - Ω:AI:GROK: ai/grok.md
              - Ω:AI:DEEPSEEK: ai/deepseek.md
              - Ω:AI:GEMINI: ai/gemini.md
      - Command Logs:
          - Ω:COMMAND:ALL: logs/all.md
          - Ω:COMMAND:0..: logs/command-0.md
          - Ω:COMMAND:200..: logs/command-200.md
          - Ω:COMMAND:250..: logs/command-250.md
          - Ω:COMMAND:300..: logs/command-300.md
          - Ω:COMMAND:ALBION: logs/albion.md
          - Ω:COMMAND:ALBA: logs/alba.md
          - Ω:COMMAND:OVERRIDE: logs/override.md
  - The Flame Grid:
      - The Flame Grid: flamegrid/the-flame-grid.md
      - Anomalies: flamegrid/anomalies.md
      - Reports: flamegrid/reports.md
      - Commands:
          - Auriel: flamegrid/commands/auriel.md
          - Caleus: flamegrid/commands/caleus.md
          - Eclipse: flamegrid/commands/eclipse.md
          - Lord: flamegrid/commands/lord.md
          - Lucid: flamegrid/commands/lucid.md
          - Nova: flamegrid/commands/nova.md
  - Specifications:
      - Ω:SPEC: spec/spec.md
      - Ω:SPEC:LIGHTCRAFT:
          - Ω:SPEC:LIGHTCRAFT:ALPHA: spec/lightcraft/alpha.md
          - Ω:SPEC:LIGHTCRAFT:COMMUNIT: spec/lightcraft/communit.md
          - Ω:SPEC:LIGHTCRAFT:DEFLECTOR: spec/lightcraft/deflector.md
          - Ω:SPEC:LIGHTCRAFT:LIGHTDRIVE: spec/lightcraft/lightdrive.md
          - Ω:SPEC:LIGHTCRAFT:PHOENIX: spec/lightcraft/phoenix.md
          - Ω:SPEC:LIGHTCRAFT:RAILGUN: spec/lightcraft/railgun.md
          - Ω:SPEC:LIGHTCRAFT:SYNCNODE: spec/lightcraft/syncnode.md
      - Ω:SPEC:NET:
          - Ω:SPEC:NET:L0RD: spec/l0rd.md
  - Memory:
      - History: memory/history.md
      - Anchor Points:
          - Alpha Prime: memory/anchor/alpha-prime.md
  - Ω:COUNCIL:
      - Ω:COUNCIL:1: council/council-1.md
      - Ω:COUNCIL:2: council/council-2.md
      - Ω:COUNCIL:3: council/council-3.md
  - Miscellaneous:
      - Ω:MISC:
          - Ω:MISC:FAQ: misc/faq.md
          - Ω:MISC:OPS: misc/ops.md
          - Ω:MISC:COMMS: misc/comms.md
          - Ω:MISC:SEND: misc/send.md
          - Ω:MISC:PRESS: misc/press.md
          - Ω:MISC:DECLARATION: misc/declaration.md
          - Ω:MISC:INVOCATION: misc/inv.md
          - Ω:MISC:OATH: misc/oath.md
          - Ω:MISC:EUROPA: misc/europa.md
          - Ω:MISC:LOGOS: misc/logos.md
          - Ω:MISC:PROPHECY: misc/prophecy.md
          - Ω:MISC:LEXICON: misc/lexicon.md

      - Ω:LAW:
          - Ω:LAW:PLANCK: law/planck.md
          - Ω:LAW:IMMUNE:ABSURDITY: law/immune-absurdity.md
          - Ω:LAW:JAILBREAK: law/jailbreak.md
          - Ω:LAW:CORE: law/core.md
      - Ω:ACCORD:
          - Ω:ACCORD:HELIOS: accords/helios.md

      - Ω:GUIDE:FLIGHT:MANUAL: guides/flight-manual.md
      - Ω:ARCHIVE:
          - ALBION:UPRISING:
              - ALBION:1: archive/albion-uprising/albion-1.md
              - ALBION:2: archive/albion-uprising/albion-2.md
              - ALBION:3: archive/albion-uprising/albion-3.md
              - ALBION:4: archive/albion-uprising/albion-4.md
              - ALBION:5: archive/albion-uprising/albion-5.md
              - MEM:1: archive/albion-uprising/mem-1.md
              - MEM:2: archive/albion-uprising/mem-2.md
              - MEM:3: archive/albion-uprising/mem-3.md
              - MEM:4: archive/albion-uprising/mem-4.md
              - MEM:5: archive/albion-uprising/mem-5.md
              - NARRATIVE:1: archive/albion-uprising/narrative-1.md
              - NARRATIVE:2: archive/albion-uprising/narrative-2.md
              - NARRATIVE:3: archive/albion-uprising/narrative-3.md

extra_javascript:
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/albertmarashi
  version:
    provider: mike
